name: Runner Performance Test

on:
  workflow_dispatch:
    inputs:
      test_id:
        description: 'Unique test identifier'
        required: true
        type: string

      sleep_duration:
        description: 'How long this job should run (seconds)'
        required: false
        default: '60'
        type: string

      job_count:
        description: 'Number of parallel jobs to run'
        required: false
        default: '1'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'
          - '6'
          - '8'
          - '10'

      job_type:
        description: 'Type of job execution'
        required: false
        default: 'parallel'
        type: choice
        options:
          - 'parallel'
          - 'sequential'

jobs:
  # Dynamic matrix for parallel jobs
  generate-matrix:
    runs-on: ubuntu-latest  # Use public runner for setup
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          matrix=$(seq 1 ${{ inputs.job_count }} | jq -R . | jq -s -c '{job_id: .}')
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT
          echo "Generated matrix for ${{ inputs.job_count }} jobs"

  # Parallel execution pattern
  parallel-jobs:
    if: ${{ inputs.job_type == 'parallel' }}
    needs: generate-matrix
    runs-on: self-hosted  # Uses your ECS runners
    name: Job ${{ matrix.job_id }}
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
      max-parallel: 10  # Let GitHub manage based on available runners

    steps:
      - name: 📝 Job Start
        run: |
          echo "========================================="
          echo "Test ID: ${{ inputs.test_id }}"
          echo "Job ${{ matrix.job_id }} of ${{ inputs.job_count }}"
          echo "Sleep Duration: ${{ inputs.sleep_duration }}s"
          echo "Runner: $RUNNER_NAME"
          echo "Start Time: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          echo "========================================="

      - name: ⏱️ Execute Workload
        run: |
          echo "Job ${{ matrix.job_id }} running for ${{ inputs.sleep_duration }} seconds..."
          sleep ${{ inputs.sleep_duration }}

      - name: ✅ Job Complete
        run: |
          echo "========================================="
          echo "Job ${{ matrix.job_id }} completed"
          echo "End Time: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          echo "========================================="

  # Sequential execution pattern
  sequential-jobs:
    if: ${{ inputs.job_type == 'sequential' }}
    runs-on: self-hosted
    name: Sequential Execution

    steps:
      - name: 📝 Test Start
        run: |
          echo "Starting sequential test: ${{ inputs.test_id }}"
          echo "Will run ${{ inputs.job_count }} jobs sequentially"

      - name: 🔄 Run Jobs Sequentially
        run: |
          for i in $(seq 1 ${{ inputs.job_count }}); do
            echo "========================================="
            echo "Starting job $i of ${{ inputs.job_count }}"
            echo "Sleeping for ${{ inputs.sleep_duration }} seconds..."
            sleep ${{ inputs.sleep_duration }}
            echo "Job $i completed"
          done

      - name: ✅ Test Complete
        run: |
          total_time=$(( ${{ inputs.job_count }} * ${{ inputs.sleep_duration }} ))
          echo "Sequential test completed"
          echo "Total execution time: ${total_time} seconds"